export const FORM_VALIDATION = 'FORM_VALIDATION';
export const FORM_VALIDATION_SUCCESS = 'FORM_VALIDATION';
export const FORM_VALIDATION_ERROR = 'FORM_VALIDATION';

export const CARD_CREATE = 'CARD_CREATE';
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS';
export const CARD_CREATE_ERROR = 'CARD_CREATE_ERROR';

export const CARD_READ = 'CARD_READ';
export const CARD_READ_SUCCESS = 'CARD_READ_SUCCESS';
export const CARD_READ_ERROR = 'CARD_READ_ERROR';